### PR TITLE
Feat/swap formik to react hook form 44

### LINKED ISSUE #44: Swap Formik to react-hook-form
Formik is large and outdated maybe idk

react-hook-form is smaller faster and better
it also works well with Yup so we can keep our validation objects.

### PR DESCRIPTION
**Pull request by GRA0007**
Closes #44 

This is a pretty big commit, and changes how forms work. See https://www.react-hook-form.com/ for documentation. Yup has also been removed in favour of react-hook-form's native validation objects.

I also noticed that the backend no longer returns error messages the same way as it used to, i.e. it doesn't specify which field is incorrect when returning that the club ID already exists (when creating a new club), so I've removed the code for that for now, but it's something I'd like to add back in the future, ideally with some documentation about how error objects should be formatted from the backend.

### CODE REVIEW

**Review by giraugh — COMMENTED** [review]
This looks good and cleaner than with formik. I'm only just barely on top of how it functions but it all looks pretty neat to me. There's a couple of very long lines so I might just make a commit that runs it all through prettier.

**Comment by GRA0007** [comment]
> This looks good and cleaner than with formik. I'm only just barely on top of how it functions but it all looks pretty neat to me. There's a couple of very long lines so I might just make a commit that runs it all through prettier.

go ahead :)

**Comment by giraugh** [comment]
Also, this is super minor but there is *some* amount of overlap between the login and signup forms. We could look into extracting out the form elements in the future perhaps?

**Review by giraugh — APPROVED** [review]

**Comment by GRA0007** [comment]
> Also, this is super minor but there is _some_ amount of overlap between the login and signup forms. We could look into extracting out the form elements in the future perhaps?

Yeah that's a good idea, maybe we should make an issue for that so we don't forget

**Pull request merged**
