### PR TITLE
Feat/custom datetime picker 103

### LINKED ISSUE #103: Custom datetime picker for event creation
In firefox the `datetime-local` input type is not supported. Additionally, events should support at start _and_ end datetime. We need a custom datetime picker, that potentially also has an option for recurring events (see #70), or we could put that input separately.

### PR DESCRIPTION
**Pull request by GRA0007**
Closes #103 

image

This is actually mostly based of the browser date and time inputs (that are supported in firefox!), I figured there's no point recreating these if they already work so well. The recurring part is also mostly done, but may need to be cleaned up/added to when we get up to #70

### CODE REVIEW

**Comment by GRA0007** [comment]
Oh and I also took the liberty of making a custom checkbox (and radio button) while I was adding them to the date picker, so they should look extra cool site-wide now

**Review by LinusKay — CHANGES_REQUESTED** [review]
Setting date/time works smoothly. Current implementation allows creation of events that end before they start, which doesn't appear to be compatible with our universe's linear implementation of time (Which I doubt will change in any upcoming releases). Could cause some concern. 
image

Other than that, great stuff.

**Comment by GRA0007** [comment]
Ah, yes, well, while we don't yet have end times implemented, I didn't bother adding any validation because the end time field isn't used yet, but I suppose I could add that in despite that it's not used yet

**Review by LinusKay — APPROVED** [review]

**Comment by GRA0007** [comment]
I'll table that for later ;)

**Pull request merged**
