### PR TITLE
Add privacy policy at /privacy page

### LINKED ISSUE #65: Write up a privacy policy
We need a privacy policy that addresses information Stevent collects from users, and notes that users under 13 are not allowed on the platform.

### PR DESCRIPTION
**Pull request by GRA0007**
Closes #65 

Please read over the new policy carefully to make sure it covers everything. This should be sufficient for now and includes a section on child's policy, disallowing users under 13 from using the site.

### CODE REVIEW

**Comment by giraugh** [comment]
Woah, this is looking super impressive and detailed. I found a few small things to double check.

Should this be "USA" or "Australia"? Is this US specific information?
> Whilst using Stevent you may use personally identifiable Student Data that in the USA is protected as defined in the Family Educational Rights and Privacy Act ("FERPA"), 20 U.S.C. § 1232(g). Stevent agrees to treat Student Data as confidential and not to share it with third parties other than as described herein.

It's also worth noting that as of now, Stevent is not an official Australian business in any capacity.

GDPR bit looks solid 👍

**Comment by GRA0007** [comment]
Yeah honestly I copied most of that from Edstem's privacy policy, I figured
if we ever do expand to the US, there's no harm in having it. I suppose we
could remove it because if that even happened it would be very far off

**Review by LinusKay — COMMENTED** [review]
All reads pretty solidly to me. Decently thorough on each point.

**Comment by GRA0007** [comment]
@Prydeton could you also take a quick look at this one before I merge, I feel like we should get everyone's eyes on this change

**Review by Prydeton — APPROVED** [review]
The privacy policy seems to be thorough and covers all required points.

**Pull request merged**
