### PR TITLE
Feat/affiliated checkbox 102

### LINKED ISSUE #102: Add a checkbox to the club creation form for RUSU affiliated clubs
There should already be a `Checkbox` component that Ewan created for the over 13 task

### PR DESCRIPTION
**Pull request by GRA0007**
Closes #102 

This should be all that's needed to store the value in the datastore. In future, I'd like this field to be more like, which organisation are you affiliated with: RUSU, RMIT Creative Collective, RMIT Sport, etc.

### CODE REVIEW

**Review by LinusKay — COMMENTED** [review]
Clubs seem to be marked as affiliated whether I check the box or not. (See my several infoTech clubs all marked as RUSU) Someone else give it a test?

**Comment by GRA0007** [comment]
eck I'll see what's going wrong

**Comment by GRA0007** [comment]
Ah looks like it was saving fine @LinusKay but since the datastore converts the boolean to a string, it was always true when showing the badge, whether it was `true` or `false`. I fixed that in the most recent commit

**Review by Prydeton — APPROVED** [review]
Looks good. Could possibly be improved by moving the text and checkbox closer together.

**Pull request merged**
