### PR TITLE
Add "alpha" label to nav bar

### PR DESCRIPTION
**Pull request by giraugh**
image

### CODE REVIEW

**Comment by GRA0007** [comment]
I fixed up the spacing just a weeeee bit
image

**Review by GRA0007 — APPROVED** [review]
pls turn off the brackets in the inline functions 😢

**Comment by giraugh** [comment]
Will do :)

**Comment by giraugh** [comment]
> I fixed up the spacing just a weeeee bit
> image
> 

Having them as sibling elements makes a lot of sense 👍

**Pull request merged**
